### ISSUE TITLE
Test `dev.bat` to run properly on windows

### ISSUE THREAD

**Issue by martenwallewein** [netsys-lab/scion-orchestrator#7]
So far the development setup on windows is not battle tested. There is need to test if the `dev.bat` is working properly (it should build the SCION binaries and copy them into bin/). In my VM things were not building for an unknown reason, so maybe someone with git and go installed on a windows machine can test this.

**Comment by martenwallewein** [comment]
Steps to reproduce: 
- run git clone
- cd scion-orchestrator
- open cmd here
- type `dev.bat` and press enter

**Comment by lschulz** [comment]
I wrote a powershell script for building SCION on Windows (#13).

Usage is: `.\dev.ps1 -Repository https://github.com/scionproto/scion.git -Tag v0.12.0 -Path dev`
All arguments are optional.

**Comment by martenwallewein** [comment]
Looks good, added this to the readme.
